### ISSUE TITLE
Linux/Mac new line fix is not in NPM

### ISSUE THREAD

**Issue by shov** [Malk123/simple-annotation#3]
At first, let me say thank you for such a package it's great, it's what I looked for!
#2 is a PR that has to be in NPM, please make a release, thank you.

**Comment by shov** [comment]
@Malk123 Hey, check it please

**Comment by shov** [comment]
@Malk123 Hey, check it please

**Comment by Malk123** [comment]
Now i watching this Project and get Notifications^^

https://github.com/Malk123/simple-annotation/releases/tag/0.1.6
